listener 1883
protocol mqtt

<<<<<<< feature/k8s_proposal
listener 9001
=======
listen 9001
>>>>>>> main
protocol websockets

# Cambio: Desactivamos anónimos y apuntamos al fichero de passwords
allow_anonymous false
password_file /mosquitto/config/pwdfile

# persistence true
# persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout