services:
  # Base de Datos: PostgreSQL 16
  db:
    image: postgres:16-alpine
    container_name: home_db
    hostname: home_db
    restart: always
    environment:
      POSTGRES_DB: home_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123 # Cambia esto en producción
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d home_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Broker MQTT: Mosquitto
  broker:
    image: eclipse-mosquitto:2.0
    container_name: home_broker
    hostname: home_broker_server
    restart: always
    ports:
      - "1883:1883" # Puerto MQTT estándar
      - "9001:9001" # WebSockets (por si quieres un dashboard web)
    env_file:
      - .env.local
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/init.sh:/init.sh:ro
    entrypoint: [ "/init.sh" ]

  migrations:
    container_name: home-db-migrations
    image: home-api:0.1.0
    build:
      context: .
      dockerfile: ./api/Dockerfile
    env_file:
      - .env.local
    # Sobrescribimos el comando para que solo ejecute Alembic y se cierre
    command: [ "alembic", "upgrade", "head" ]
    depends_on:
      db:
        condition: service_healthy

  home_api:
    container_name: home-api
    image: home-api:0.1.0
    build:
      context: .
      dockerfile: ./api/Dockerfile
    hostname: home_api
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully # Solo arranca si la migración terminó bien

  home_subscriber:
    container_name: home-subscriber
    image: home-subscriber:0.1.0
    build:
      context: .
      dockerfile: ./subscriber/Dockerfile
    hostname: home_subscriber
    restart: unless-stopped
    env_file:
      - .env.local
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
      broker:
        condition: service_started

  home_publisher:
    container_name: home-publisher
    image: home-publisher:0.1.0
    build:
      context: .
      dockerfile: ./publisher/Dockerfile
    hostname: home_publisher
    restart: unless-stopped
    env_file:
      - .env.local
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
      broker:
        condition: service_started

volumes:
  postgres_data:
  grafana: