apiVersion: v1
kind: Secret
metadata:
  name: home-iot-secrets
  namespace: home-iot
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password123"
  MQTT_USERNAME: ""
  MQTT_PASSWORD: ""
  DATABASE_URL: "postgresql+asyncpg://postgres:password123@home-postgres:5432/home_db"
