apiVersion: v1
kind: Secret
metadata:
  name: home-iot-secrets
  namespace: home-iot
type: Opaque
stringData:
  # Credenciales para PostgreSQL
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password123"
  
  # Credenciales para Mosquitto (Las que usa el Init Container)
  MQTT_USERNAME: "home_admin"
  MQTT_PASSWORD: "secure_mqtt_password"
  
  # URL de conexión (Asegúrate de que coincida con el usuario/pass de arriba si la API la usa)
  DATABASE_URL: "postgresql+psycopg://postgres:password123@home-postgres:5432/home_db"