apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-iot-ingress
  namespace: home-iot
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "web"
spec:
  rules:
  - host: home-iot.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: home-api
            port:
              number: 80
