"""Se añade campo para saber si un dispositivo puede ser leido

Revision ID: 4db20fd28a79
Revises: 529dd0c409d6
Create Date: 2026-03-13 16:51:56.927804

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4db20fd28a79'
down_revision: Union[str, Sequence[str], None] = '529dd0c409d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('read_enabled', sa.Boolean(), default=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'read_enabled')
    # ### end Alembic commands ###
