"""Primera migración de datos

Revision ID: 529dd0c409d6
Revises: 
Create Date: 2026-03-13 14:43:30.671890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '529dd0c409d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry',
    sa.Column('id_telemetry', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('extra_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id_item'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_telemetry')
    )
    op.create_index('idx_device_telemetry_time', 'telemetry', ['device_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_telemetry_created_at'), 'telemetry', ['created_at'], unique=False)
    op.alter_column('devices', 'extra_info',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'extra_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_telemetry_created_at'), table_name='telemetry')
    op.drop_index('idx_device_telemetry_time', table_name='telemetry')
    op.drop_table('telemetry')
    # ### end Alembic commands ###
