"""initial_schema

Revision ID: 563b53e122c6
Revises: 
Create Date: 2026-04-14 15:18:47.588783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '563b53e122c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installations',
    sa.Column('id_item', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('topic_prefix', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_item'),
    sa.UniqueConstraint('topic_prefix')
    )
    op.create_table('zones',
    sa.Column('id_item', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id_item'], ),
    sa.PrimaryKeyConstraint('id_item')
    )
    op.create_table('devices',
    sa.Column('id_item', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('extra_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('read_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id_item'], ),
    sa.PrimaryKeyConstraint('id_item'),
    sa.UniqueConstraint('topic')
    )
    op.create_table('telemetry',
    sa.Column('id_telemetry', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('extra_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id_item'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_telemetry')
    )
    op.create_index('idx_device_telemetry_time', 'telemetry', ['device_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_telemetry_created_at'), 'telemetry', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_created_at'), table_name='telemetry')
    op.drop_index('idx_device_telemetry_time', table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_table('devices')
    op.drop_table('zones')
    op.drop_table('installations')
    # ### end Alembic commands ###
