[project]
name = "publisher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiomqtt>=2.5.1",
    "apscheduler~=3.11.2",
    "pytz~=2026.1",
    "shared",
]

[tool.uv.sources]
shared = { workspace = true, editable = true }
